/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.KafkaDemo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3554056200868965473L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.example.KafkaDemo\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"orderId\",\"type\":\"int\",\"doc\":\"The id of the order.\"},{\"name\":\"orderTime\",\"type\":\"int\",\"doc\":\"Timestamp of the order.\"},{\"name\":\"orderAddress\",\"type\":\"string\",\"doc\":\"The address of the order.\"},{\"name\":\"orderSource\",\"type\":\"string\",\"doc\":\"The source of the order.\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<Order>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Order> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Order to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Order from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Order instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The id of the order. */
  @Deprecated public int orderId;
  /** Timestamp of the order. */
  @Deprecated public int orderTime;
  /** The address of the order. */
  @Deprecated public java.lang.CharSequence orderAddress;
  /** The source of the order. */
  @Deprecated public java.lang.CharSequence orderSource;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param orderId The id of the order.
   * @param orderTime Timestamp of the order.
   * @param orderAddress The address of the order.
   * @param orderSource The source of the order.
   */
  public Order(java.lang.Integer orderId, java.lang.Integer orderTime, java.lang.CharSequence orderAddress, java.lang.CharSequence orderSource) {
    this.orderId = orderId;
    this.orderTime = orderTime;
    this.orderAddress = orderAddress;
    this.orderSource = orderSource;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return orderTime;
    case 2: return orderAddress;
    case 3: return orderSource;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.Integer)value$; break;
    case 1: orderTime = (java.lang.Integer)value$; break;
    case 2: orderAddress = (java.lang.CharSequence)value$; break;
    case 3: orderSource = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The id of the order.
   */
  public int getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * The id of the order.
   * @param value the value to set.
   */
  public void setOrderId(int value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderTime' field.
   * @return Timestamp of the order.
   */
  public int getOrderTime() {
    return orderTime;
  }


  /**
   * Sets the value of the 'orderTime' field.
   * Timestamp of the order.
   * @param value the value to set.
   */
  public void setOrderTime(int value) {
    this.orderTime = value;
  }

  /**
   * Gets the value of the 'orderAddress' field.
   * @return The address of the order.
   */
  public java.lang.CharSequence getOrderAddress() {
    return orderAddress;
  }


  /**
   * Sets the value of the 'orderAddress' field.
   * The address of the order.
   * @param value the value to set.
   */
  public void setOrderAddress(java.lang.CharSequence value) {
    this.orderAddress = value;
  }

  /**
   * Gets the value of the 'orderSource' field.
   * @return The source of the order.
   */
  public java.lang.CharSequence getOrderSource() {
    return orderSource;
  }


  /**
   * Sets the value of the 'orderSource' field.
   * The source of the order.
   * @param value the value to set.
   */
  public void setOrderSource(java.lang.CharSequence value) {
    this.orderSource = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.example.KafkaDemo.Order.Builder newBuilder() {
    return new com.example.KafkaDemo.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.example.KafkaDemo.Order.Builder newBuilder(com.example.KafkaDemo.Order.Builder other) {
    if (other == null) {
      return new com.example.KafkaDemo.Order.Builder();
    } else {
      return new com.example.KafkaDemo.Order.Builder(other);
    }
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.example.KafkaDemo.Order.Builder newBuilder(com.example.KafkaDemo.Order other) {
    if (other == null) {
      return new com.example.KafkaDemo.Order.Builder();
    } else {
      return new com.example.KafkaDemo.Order.Builder(other);
    }
  }

  /**
   * RecordBuilder for Order instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    /** The id of the order. */
    private int orderId;
    /** Timestamp of the order. */
    private int orderTime;
    /** The address of the order. */
    private java.lang.CharSequence orderAddress;
    /** The source of the order. */
    private java.lang.CharSequence orderSource;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.KafkaDemo.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderTime)) {
        this.orderTime = data().deepCopy(fields()[1].schema(), other.orderTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderAddress)) {
        this.orderAddress = data().deepCopy(fields()[2].schema(), other.orderAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.orderSource)) {
        this.orderSource = data().deepCopy(fields()[3].schema(), other.orderSource);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.KafkaDemo.Order other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderTime)) {
        this.orderTime = data().deepCopy(fields()[1].schema(), other.orderTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderAddress)) {
        this.orderAddress = data().deepCopy(fields()[2].schema(), other.orderAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderSource)) {
        this.orderSource = data().deepCopy(fields()[3].schema(), other.orderSource);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * The id of the order.
      * @return The value.
      */
    public int getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * The id of the order.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder setOrderId(int value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * The id of the order.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * The id of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderTime' field.
      * Timestamp of the order.
      * @return The value.
      */
    public int getOrderTime() {
      return orderTime;
    }


    /**
      * Sets the value of the 'orderTime' field.
      * Timestamp of the order.
      * @param value The value of 'orderTime'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder setOrderTime(int value) {
      validate(fields()[1], value);
      this.orderTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderTime' field has been set.
      * Timestamp of the order.
      * @return True if the 'orderTime' field has been set, false otherwise.
      */
    public boolean hasOrderTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderTime' field.
      * Timestamp of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder clearOrderTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderAddress' field.
      * The address of the order.
      * @return The value.
      */
    public java.lang.CharSequence getOrderAddress() {
      return orderAddress;
    }


    /**
      * Sets the value of the 'orderAddress' field.
      * The address of the order.
      * @param value The value of 'orderAddress'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder setOrderAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.orderAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderAddress' field has been set.
      * The address of the order.
      * @return True if the 'orderAddress' field has been set, false otherwise.
      */
    public boolean hasOrderAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderAddress' field.
      * The address of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder clearOrderAddress() {
      orderAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderSource' field.
      * The source of the order.
      * @return The value.
      */
    public java.lang.CharSequence getOrderSource() {
      return orderSource;
    }


    /**
      * Sets the value of the 'orderSource' field.
      * The source of the order.
      * @param value The value of 'orderSource'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder setOrderSource(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.orderSource = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderSource' field has been set.
      * The source of the order.
      * @return True if the 'orderSource' field has been set, false otherwise.
      */
    public boolean hasOrderSource() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderSource' field.
      * The source of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Order.Builder clearOrderSource() {
      orderSource = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.Integer) defaultValue(fields()[0]);
        record.orderTime = fieldSetFlags()[1] ? this.orderTime : (java.lang.Integer) defaultValue(fields()[1]);
        record.orderAddress = fieldSetFlags()[2] ? this.orderAddress : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.orderSource = fieldSetFlags()[3] ? this.orderSource : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.orderId);

    out.writeInt(this.orderTime);

    out.writeString(this.orderAddress);

    out.writeString(this.orderSource);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readInt();

      this.orderTime = in.readInt();

      this.orderAddress = in.readString(this.orderAddress instanceof Utf8 ? (Utf8)this.orderAddress : null);

      this.orderSource = in.readString(this.orderSource instanceof Utf8 ? (Utf8)this.orderSource : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readInt();
          break;

        case 1:
          this.orderTime = in.readInt();
          break;

        case 2:
          this.orderAddress = in.readString(this.orderAddress instanceof Utf8 ? (Utf8)this.orderAddress : null);
          break;

        case 3:
          this.orderSource = in.readString(this.orderSource instanceof Utf8 ? (Utf8)this.orderSource : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










