/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.KafkaDemo;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class Payment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8488289658989031316L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Payment\",\"namespace\":\"com.example.KafkaDemo\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"int\",\"doc\":\"The id of the order.\"},{\"name\":\"paymentTime\",\"type\":\"int\",\"doc\":\"Timestamp of the order.\"},{\"name\":\"paymentAddress\",\"type\":\"string\",\"doc\":\"The address of the order.\"},{\"name\":\"paymentGateway\",\"type\":\"string\",\"doc\":\"The address of the order.\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Payment> ENCODER =
      new BinaryMessageEncoder<Payment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Payment> DECODER =
      new BinaryMessageDecoder<Payment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Payment> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Payment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Payment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Payment>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Payment to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Payment from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Payment instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Payment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The id of the order. */
  @Deprecated public int paymentId;
  /** Timestamp of the order. */
  @Deprecated public int paymentTime;
  /** The address of the order. */
  @Deprecated public java.lang.CharSequence paymentAddress;
  /** The address of the order. */
  @Deprecated public java.lang.CharSequence paymentGateway;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Payment() {}

  /**
   * All-args constructor.
   * @param paymentId The id of the order.
   * @param paymentTime Timestamp of the order.
   * @param paymentAddress The address of the order.
   * @param paymentGateway The address of the order.
   */
  public Payment(java.lang.Integer paymentId, java.lang.Integer paymentTime, java.lang.CharSequence paymentAddress, java.lang.CharSequence paymentGateway) {
    this.paymentId = paymentId;
    this.paymentTime = paymentTime;
    this.paymentAddress = paymentAddress;
    this.paymentGateway = paymentGateway;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return paymentTime;
    case 2: return paymentAddress;
    case 3: return paymentGateway;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.Integer)value$; break;
    case 1: paymentTime = (java.lang.Integer)value$; break;
    case 2: paymentAddress = (java.lang.CharSequence)value$; break;
    case 3: paymentGateway = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The id of the order.
   */
  public int getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * The id of the order.
   * @param value the value to set.
   */
  public void setPaymentId(int value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'paymentTime' field.
   * @return Timestamp of the order.
   */
  public int getPaymentTime() {
    return paymentTime;
  }


  /**
   * Sets the value of the 'paymentTime' field.
   * Timestamp of the order.
   * @param value the value to set.
   */
  public void setPaymentTime(int value) {
    this.paymentTime = value;
  }

  /**
   * Gets the value of the 'paymentAddress' field.
   * @return The address of the order.
   */
  public java.lang.CharSequence getPaymentAddress() {
    return paymentAddress;
  }


  /**
   * Sets the value of the 'paymentAddress' field.
   * The address of the order.
   * @param value the value to set.
   */
  public void setPaymentAddress(java.lang.CharSequence value) {
    this.paymentAddress = value;
  }

  /**
   * Gets the value of the 'paymentGateway' field.
   * @return The address of the order.
   */
  public java.lang.CharSequence getPaymentGateway() {
    return paymentGateway;
  }


  /**
   * Sets the value of the 'paymentGateway' field.
   * The address of the order.
   * @param value the value to set.
   */
  public void setPaymentGateway(java.lang.CharSequence value) {
    this.paymentGateway = value;
  }

  /**
   * Creates a new Payment RecordBuilder.
   * @return A new Payment RecordBuilder
   */
  public static com.example.KafkaDemo.Payment.Builder newBuilder() {
    return new com.example.KafkaDemo.Payment.Builder();
  }

  /**
   * Creates a new Payment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Payment RecordBuilder
   */
  public static com.example.KafkaDemo.Payment.Builder newBuilder(com.example.KafkaDemo.Payment.Builder other) {
    if (other == null) {
      return new com.example.KafkaDemo.Payment.Builder();
    } else {
      return new com.example.KafkaDemo.Payment.Builder(other);
    }
  }

  /**
   * Creates a new Payment RecordBuilder by copying an existing Payment instance.
   * @param other The existing instance to copy.
   * @return A new Payment RecordBuilder
   */
  public static com.example.KafkaDemo.Payment.Builder newBuilder(com.example.KafkaDemo.Payment other) {
    if (other == null) {
      return new com.example.KafkaDemo.Payment.Builder();
    } else {
      return new com.example.KafkaDemo.Payment.Builder(other);
    }
  }

  /**
   * RecordBuilder for Payment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Payment>
    implements org.apache.avro.data.RecordBuilder<Payment> {

    /** The id of the order. */
    private int paymentId;
    /** Timestamp of the order. */
    private int paymentTime;
    /** The address of the order. */
    private java.lang.CharSequence paymentAddress;
    /** The address of the order. */
    private java.lang.CharSequence paymentGateway;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.KafkaDemo.Payment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.paymentTime)) {
        this.paymentTime = data().deepCopy(fields()[1].schema(), other.paymentTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentAddress)) {
        this.paymentAddress = data().deepCopy(fields()[2].schema(), other.paymentAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.paymentGateway)) {
        this.paymentGateway = data().deepCopy(fields()[3].schema(), other.paymentGateway);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Payment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.KafkaDemo.Payment other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentTime)) {
        this.paymentTime = data().deepCopy(fields()[1].schema(), other.paymentTime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentAddress)) {
        this.paymentAddress = data().deepCopy(fields()[2].schema(), other.paymentAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentGateway)) {
        this.paymentGateway = data().deepCopy(fields()[3].schema(), other.paymentGateway);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * The id of the order.
      * @return The value.
      */
    public int getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * The id of the order.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder setPaymentId(int value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * The id of the order.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * The id of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder clearPaymentId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentTime' field.
      * Timestamp of the order.
      * @return The value.
      */
    public int getPaymentTime() {
      return paymentTime;
    }


    /**
      * Sets the value of the 'paymentTime' field.
      * Timestamp of the order.
      * @param value The value of 'paymentTime'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder setPaymentTime(int value) {
      validate(fields()[1], value);
      this.paymentTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentTime' field has been set.
      * Timestamp of the order.
      * @return True if the 'paymentTime' field has been set, false otherwise.
      */
    public boolean hasPaymentTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'paymentTime' field.
      * Timestamp of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder clearPaymentTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentAddress' field.
      * The address of the order.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentAddress() {
      return paymentAddress;
    }


    /**
      * Sets the value of the 'paymentAddress' field.
      * The address of the order.
      * @param value The value of 'paymentAddress'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder setPaymentAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.paymentAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentAddress' field has been set.
      * The address of the order.
      * @return True if the 'paymentAddress' field has been set, false otherwise.
      */
    public boolean hasPaymentAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentAddress' field.
      * The address of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder clearPaymentAddress() {
      paymentAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentGateway' field.
      * The address of the order.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentGateway() {
      return paymentGateway;
    }


    /**
      * Sets the value of the 'paymentGateway' field.
      * The address of the order.
      * @param value The value of 'paymentGateway'.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder setPaymentGateway(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.paymentGateway = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentGateway' field has been set.
      * The address of the order.
      * @return True if the 'paymentGateway' field has been set, false otherwise.
      */
    public boolean hasPaymentGateway() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paymentGateway' field.
      * The address of the order.
      * @return This builder.
      */
    public com.example.KafkaDemo.Payment.Builder clearPaymentGateway() {
      paymentGateway = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Payment build() {
      try {
        Payment record = new Payment();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.Integer) defaultValue(fields()[0]);
        record.paymentTime = fieldSetFlags()[1] ? this.paymentTime : (java.lang.Integer) defaultValue(fields()[1]);
        record.paymentAddress = fieldSetFlags()[2] ? this.paymentAddress : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.paymentGateway = fieldSetFlags()[3] ? this.paymentGateway : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Payment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Payment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Payment>
    READER$ = (org.apache.avro.io.DatumReader<Payment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.paymentId);

    out.writeInt(this.paymentTime);

    out.writeString(this.paymentAddress);

    out.writeString(this.paymentGateway);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readInt();

      this.paymentTime = in.readInt();

      this.paymentAddress = in.readString(this.paymentAddress instanceof Utf8 ? (Utf8)this.paymentAddress : null);

      this.paymentGateway = in.readString(this.paymentGateway instanceof Utf8 ? (Utf8)this.paymentGateway : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readInt();
          break;

        case 1:
          this.paymentTime = in.readInt();
          break;

        case 2:
          this.paymentAddress = in.readString(this.paymentAddress instanceof Utf8 ? (Utf8)this.paymentAddress : null);
          break;

        case 3:
          this.paymentGateway = in.readString(this.paymentGateway instanceof Utf8 ? (Utf8)this.paymentGateway : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










